version: '3'
volumes:
  web_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./resources

services:
  postgres:
    build:
      context: Database
      dockerfile: Dockerfile.dev

  api:
    build:
      context: TwitterAnalysis/
      dockerfile: Dockerfile.dev

    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - web_data:/twitteranalysis/resources