version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  api:
    build:
      context: TwitterAnalysis/
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "9000:9000"