version: '3'

services:
  postgres:
    build:
      context: Database
      dockerfile: Dockerfile.dev

  api:
    build:
      context: TwitterAnalysis/
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "9000:9000"