version: "3"
volumes:
  web_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./resources

services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  postgres:
    build:
      context: Database
      dockerfile: Dockerfile.dev

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "9999:80"

  api:
    build:
      context: TwitterAnalysis/
      dockerfile: Dockerfile.dev

    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - web_data:/twitteranalysis/resources
      - ./TwitterAnalysis:/twitteranalysis