name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker compose
      run: |
        cp .env.example .env
        docker-compose up -d --build
        
    - name: wait the container to be stable
      run: sleep 45s
      shell: bash
      
    - name: install python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
        
    - name: install dep
      working-directory: ./test_script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: run test
      working-directory: ./test_script
      run: python -m unittest test.py
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

      
      
    
